// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildNode(arg1, arg2, arg3) {
  return window['go']['app']['App']['BuildNode'](arg1, arg2, arg3);
}

export function CheckHostStatus(arg1) {
  return window['go']['app']['App']['CheckHostStatus'](arg1);
}

export function ClearLogs() {
  return window['go']['app']['App']['ClearLogs']();
}

export function CloseSSH(arg1) {
  return window['go']['app']['App']['CloseSSH'](arg1);
}

export function ConnectSSH(arg1) {
  return window['go']['app']['App']['ConnectSSH'](arg1);
}

export function CreateHost(arg1) {
  return window['go']['app']['App']['CreateHost'](arg1);
}

export function CreatePlugin(arg1, arg2) {
  return window['go']['app']['App']['CreatePlugin'](arg1, arg2);
}

export function DeleteHost(arg1) {
  return window['go']['app']['App']['DeleteHost'](arg1);
}

export function DeployNode(arg1, arg2, arg3) {
  return window['go']['app']['App']['DeployNode'](arg1, arg2, arg3);
}

export function DownloadFile(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['DownloadFile'](arg1, arg2, arg3, arg4);
}

export function Exec(arg1, arg2) {
  return window['go']['app']['App']['Exec'](arg1, arg2);
}

export function GetBuiltNodes() {
  return window['go']['app']['App']['GetBuiltNodes']();
}

export function GetDBPath() {
  return window['go']['app']['App']['GetDBPath']();
}

export function GetHostMetrics(arg1, arg2) {
  return window['go']['app']['App']['GetHostMetrics'](arg1, arg2);
}

export function GetHosts() {
  return window['go']['app']['App']['GetHosts']();
}

export function GetLogFiles() {
  return window['go']['app']['App']['GetLogFiles']();
}

export function GetLogs(arg1) {
  return window['go']['app']['App']['GetLogs'](arg1);
}

export function GetLogsByDate(arg1, arg2) {
  return window['go']['app']['App']['GetLogsByDate'](arg1, arg2);
}

export function GetNodeModules() {
  return window['go']['app']['App']['GetNodeModules']();
}

export function GetPluginSource(arg1) {
  return window['go']['app']['App']['GetPluginSource'](arg1);
}

export function GetRetentionHours() {
  return window['go']['app']['App']['GetRetentionHours']();
}

export function Greet(arg1) {
  return window['go']['app']['App']['Greet'](arg1);
}

export function InitDB() {
  return window['go']['app']['App']['InitDB']();
}

export function IsConnected(arg1) {
  return window['go']['app']['App']['IsConnected'](arg1);
}

export function LaunchRDP(arg1, arg2, arg3) {
  return window['go']['app']['App']['LaunchRDP'](arg1, arg2, arg3);
}

export function ListRemoteFiles(arg1, arg2) {
  return window['go']['app']['App']['ListRemoteFiles'](arg1, arg2);
}

export function RDPOpen(arg1) {
  return window['go']['app']['App']['RDPOpen'](arg1);
}

export function RunNode(arg1) {
  return window['go']['app']['App']['RunNode'](arg1);
}

export function SavePluginSource(arg1, arg2) {
  return window['go']['app']['App']['SavePluginSource'](arg1, arg2);
}

export function SelectFile() {
  return window['go']['app']['App']['SelectFile']();
}

export function SelectSaveFile() {
  return window['go']['app']['App']['SelectSaveFile']();
}

export function SetRetentionHours(arg1) {
  return window['go']['app']['App']['SetRetentionHours'](arg1);
}

export function TerminalClose(arg1) {
  return window['go']['app']['App']['TerminalClose'](arg1);
}

export function TerminalOpen(arg1, arg2, arg3) {
  return window['go']['app']['App']['TerminalOpen'](arg1, arg2, arg3);
}

export function TerminalResize(arg1, arg2, arg3) {
  return window['go']['app']['App']['TerminalResize'](arg1, arg2, arg3);
}

export function TerminalWrite(arg1, arg2) {
  return window['go']['app']['App']['TerminalWrite'](arg1, arg2);
}

export function UploadFile(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['UploadFile'](arg1, arg2, arg3, arg4);
}
