// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {monitor} from '../models';
import {host} from '../models';
import {node} from '../models';
import {session} from '../models';

export function BuildNode(arg1:Array<string>,arg2:string,arg3:string):Promise<string>;

export function CheckHostStatus(arg1:number):Promise<monitor.HostStatus>;

export function ClearLogs():Promise<void>;

export function CloseSSH(arg1:number):Promise<void>;

export function ConnectSSH(arg1:number):Promise<void>;

export function CreateHost(arg1:host.Host):Promise<void>;

export function CreatePlugin(arg1:string,arg2:string):Promise<void>;

export function DeleteHost(arg1:number):Promise<void>;

export function DeployNode(arg1:number,arg2:string,arg3:string):Promise<string>;

export function DownloadFile(arg1:number,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function Exec(arg1:number,arg2:string):Promise<string>;

export function GetBuiltNodes():Promise<Array<string>>;

export function GetDBPath():Promise<string>;

export function GetHost(arg1:number):Promise<host.Host>;

export function GetHostMetrics(arg1:number,arg2:string):Promise<Array<monitor.MetricPoint>>;

export function GetHosts():Promise<Array<host.Host>>;

export function GetLogFiles():Promise<Array<string>>;

export function GetLogs(arg1:number):Promise<Array<string>>;

export function GetLogsByDate(arg1:string,arg2:number):Promise<Array<string>>;

export function GetNodeModules():Promise<Array<node.Plugin>>;

export function GetPluginSource(arg1:string):Promise<string>;

export function GetRetentionHours():Promise<number>;

export function Greet(arg1:string):Promise<string>;

export function InitDB():Promise<void>;

export function IsConnected(arg1:number):Promise<boolean>;

export function LaunchRDP(arg1:number,arg2:number,arg3:number):Promise<void>;

export function ListRemoteFiles(arg1:number,arg2:string):Promise<Array<session.FileInfo>>;

export function RDPOpen(arg1:number):Promise<void>;

export function RemoveRemoteFile(arg1:number,arg2:string):Promise<void>;

export function RunNode(arg1:number):Promise<string>;

export function SavePluginSource(arg1:string,arg2:string):Promise<void>;

export function SelectFile():Promise<string>;

export function SelectSaveFile():Promise<string>;

export function SetRetentionHours(arg1:number):Promise<void>;

export function TerminalClose(arg1:string):Promise<void>;

export function TerminalOpen(arg1:number,arg2:number,arg3:number):Promise<string>;

export function TerminalResize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function TerminalWrite(arg1:string,arg2:string):Promise<void>;

export function UpdateHost(arg1:host.Host):Promise<void>;

export function UploadFile(arg1:number,arg2:string,arg3:string,arg4:boolean):Promise<void>;
